#!/usr/bin/env bash
#
# Builds the worker's .env.local from your local one and pipes it straight to
# the EC2 box over SSH. Values are never printed -- only variable names.
#
#   ./deploy/ec2/push-env.sh ~/keys/erp.pem 13.234.x.x
#   ./deploy/ec2/push-env.sh ~/keys/erp.pem 13.234.x.x https://cha-erp-web.vercel.app
#
set -euo pipefail

KEY="${1:-}"
HOST="${2:-}"
APP_URL="${3:-https://cha-erp-web.vercel.app}"
SSH_USER="${SSH_USER:-ubuntu}"
REMOTE="/opt/erp/checklist-app/.env.local"

if [[ -z "$KEY" || -z "$HOST" ]]; then
  echo "usage: $0 <key.pem> <host> [app-url]" >&2
  exit 1
fi
APP_URL="${APP_URL%/}"

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
ENV_FILE="$REPO/.env.local"
[[ -f "$ENV_FILE" ]] || { echo "ERROR: $ENV_FILE not found." >&2; exit 1; }

# shellcheck disable=SC1090
set -a; . "$ENV_FILE"; set +a

# Overrides -- these must differ from the dev file.
GRAPH_TRANSPORT=graph
NEXT_PUBLIC_APP_URL="$APP_URL"
MS_REDIRECT_URI="$APP_URL/api/integrations/microsoft/callback"
# Region-neutral: it lands in claim_mail_connection.locked_by, so a wrong
# region baked into the name misleads whoever debugs a stuck lock later.
WORKER_INSTANCE_ID="${WORKER_INSTANCE_ID:-ec2-1}"
WORKER_TICK_SECONDS="${WORKER_TICK_SECONDS:-60}"
WORKER_MAILBOX_INTERVAL_SECONDS="${WORKER_MAILBOX_INTERVAL_SECONDS:-300}"
LOG_LEVEL="${LOG_LEVEL:-info}"

# Only what the worker reads. RESEND_*/MAIL_* are web-only (no mailEnv() call
# on the worker path), SEED_ADMIN_* is a local script, VERCEL_OIDC_TOKEN is
# Vercel CLI scratch that `vercel link` appended.
VARS=(
  NEXT_PUBLIC_SUPABASE_URL NEXT_PUBLIC_SUPABASE_ANON_KEY NEXT_PUBLIC_APP_URL
  SUPABASE_SERVICE_ROLE_KEY
  MS_CLIENT_ID MS_CLIENT_SECRET MS_REDIRECT_URI MS_TENANT_ID
  TOKEN_ENCRYPTION_KEY GRAPH_TRANSPORT
  OPENAI_API_KEY
  WORKER_INSTANCE_ID WORKER_TICK_SECONDS WORKER_MAILBOX_INTERVAL_SECONDS LOG_LEVEL
)

missing=()
for n in "${VARS[@]}"; do [[ -z "${!n:-}" ]] && missing+=("$n"); done
if (( ${#missing[@]} )); then
  echo "ERROR: empty in $ENV_FILE:" >&2; printf '  %s\n' "${missing[@]}" >&2; exit 1
fi

echo "Sending ${#VARS[@]} variables to $SSH_USER@$HOST:$REMOTE"
printf '  %s\n' "${VARS[@]}"

{
  echo "# Generated by deploy/ec2/push-env.sh -- do not edit by hand."
  for n in "${VARS[@]}"; do
    v="${!n}"
    v="${v//\\/\\\\}"   # escape backslashes first
    v="${v//\"/\\\"}"   # then double quotes
    printf '%s="%s"\n' "$n" "$v"
  done
} | ssh -i "$KEY" "$SSH_USER@$HOST" \
      "sudo tee $REMOTE >/dev/null && sudo chown erp:erp $REMOTE && sudo chmod 600 $REMOTE"

echo
echo "Done. Start the worker with:"
echo "  ssh -i $KEY $SSH_USER@$HOST 'sudo systemctl enable --now erp-mail-watcher'"
