import 'server-only';
import { isBondCode } from '@checklist/core';
import type {
  BondOrCertificate,
  ChecklistDraft,
  DraftSupportingDoc,
  HssParty,
} from '@checklist/extraction';
import type { Database } from '@checklist/db';
import { serviceClient } from '@/lib/supabase/admin';

/**
 * Resolving the three sheets whose sources are held by a person, not a document:
 * HSS, BONDS_CERTIFICATES and the eSanchit half of SUPPORTING_DOCS.
 *
 * Each of the three is a fact the shipping documents cannot carry in full:
 *
 *   - a high-seas seller's IE Code and branch serial are on the high-seas-sale
 *     agreement or in the importer's mail, and ICES rejects an unregistered
 *     branch outright (error 163), so there is no safe default;
 *   - a bond's number and registration port are on a document Customs issued,
 *     and its *state* — credited, expired, closed — is invisible to us entirely
 *     (ICES 504, 505, 506);
 *   - an eSanchit IRN is generated by ICEGATE at upload and exists nowhere else.
 *
 * So all three read from operator tables, and this runs after the header
 * resolution because `boe.flags.hss` is what decides whether the HSS chain is
 * declared at all.
 *
 * Not to be confused with `importer_line_securities` behind
 * `/settings/securities`, which is a container deposit lodged with a *shipping
 * line* for delivery orders. These are bonds executed with *Customs*.
 *
 * Contracts: docs/boe-mapping/16-hss.md, 17-bonds-certificates.md,
 * 18-supporting-docs.md.
 */

type HssRow = Database['public']['Tables']['job_hss_chain']['Row'];
type BondRow = Database['public']['Tables']['job_bonds_certificates']['Row'];
type EsanchitRow = Database['public']['Tables']['job_document_esanchit']['Row'];
type DocumentRow = Database['public']['Tables']['job_documents']['Row'];

export interface SecuritiesResolutionInput {
  draft: ChecklistDraft;
  companyId: string;
  jobId: string;
}

/** Fill `draft.hssChain`, `draft.bonds`, and the eSanchit fields on the documents. */
export async function applySecuritiesResolution({
  draft,
  companyId,
  jobId,
}: SecuritiesResolutionInput): Promise<ChecklistDraft> {
  const db = serviceClient();
  const scope = { job_id: jobId, company_id: companyId };

  const [{ data: hssRows }, { data: bondRows }, { data: esanchitRows }, { data: documentRows }] =
    await Promise.all([
      db.from('job_hss_chain').select('*').match(scope).order('level', { ascending: true }),
      db.from('job_bonds_certificates').select('*').match(scope).order('seq', { ascending: true }),
      db.from('job_document_esanchit').select('*').match(scope),
      db.from('job_documents').select('*').match(scope),
    ]);

  const flags = draft.flags.filter((f) => !f.path?.startsWith('securities.'));
  const warn = (path: string, message: string) =>
    flags.push({ severity: 'warning', path: `securities.${path}`, message });

  const hssChain = (hssRows ?? []).map(toHssParty);
  const bonds = proposeBonds(draft, (bondRows ?? []).map(toBondOrCertificate), warn);
  const supportingDocs = attachEsanchit(
    draft.supportingDocs ?? [],
    (esanchitRows ?? []) as EsanchitRow[],
    (documentRows ?? []) as DocumentRow[],
  );

  return {
    ...draft,
    ...(hssChain.length && { hssChain }),
    ...(bonds.length && { bonds }),
    supportingDocs,
    flags,
  };
}

function toHssParty(row: HssRow): HssParty {
  return {
    level: row.level,
    iec: row.iec,
    ...(row.branch_sr_no != null && { branchSrNo: row.branch_sr_no }),
    ...(row.name && { name: row.name }),
    ...(row.branch_name && { branchName: row.branch_name }),
    ...(row.ad_code && { adCode: row.ad_code }),
    ...(row.address && { address: row.address }),
    ...(row.city && { city: row.city }),
    ...(row.country && { country: row.country }),
    ...(row.postal_code && { postalCode: row.postal_code }),
  };
}

function toBondOrCertificate(row: BondRow): BondOrCertificate {
  return {
    kind: row.kind,
    type: row.type,
    number: row.number,
    ...(row.cert_date && { date: row.cert_date }),
    ...(row.commissionerate && { commissionerate: row.commissionerate }),
    ...(row.division && { division: row.division }),
    ...(row.range_office && { range: row.range_office }),
    ...(row.registration_port && { registrationPortCode: row.registration_port }),
    ...(row.proposed && { proposed: true }),
  };
}

/**
 * The warehousing bond the job already holds, added to whatever the operator
 * keyed — and only where they have not keyed it themselves.
 *
 * `InbondExbond.bondNo` has carried the warehouse bond since the INBOND_EXBOND
 * sheet was wired; it is the same bond ICES wants declared on both sheets, and
 * the station that licensed the warehouse is where that bond is registered.
 *
 * Nothing else is proposed. A scheme bond number is not derivable from a
 * licence number, and a bond that was live last month is one of ICES' state
 * rejections this month.
 */
function proposeBonds(
  draft: ChecklistDraft,
  keyed: BondOrCertificate[],
  warn: (path: string, message: string) => void,
): BondOrCertificate[] {
  const bonds = [...keyed];
  const warehouseBondNo = draft.inbondExbond?.bondNo?.value?.trim();

  if (warehouseBondNo && !bonds.some((b) => b.number.trim() === warehouseBondNo)) {
    // The station that licensed the warehouse is the station the warehouse bond
    // is registered at, and the warehouse code's first four characters are that
    // station (see masters/warehouse-code.ts). That is a derivation, not a
    // guess, but the operator can still override it.
    const stationCode = draft.inbondExbond?.warehouse?.value?.stationCode;
    bonds.unshift({
      kind: 'bond',
      type: 'WH',
      number: warehouseBondNo,
      ...(stationCode && { registrationPortCode: stationCode }),
      proposed: true,
    });
  }

  const beType = draft.boe?.beType.value ?? draft.beType;
  if (beType === 'Warehousing' && !bonds.some((b) => b.kind === 'bond' && b.type === 'WH')) {
    warn(
      'bonds',
      'This is a warehousing Bill of Entry and no warehouse bond is recorded. Goods are warehoused ' +
        'against a bond by definition, and ICES will not accept the filing without its number ' +
        '(error 502) — key it on the bond panel.',
    );
  }

  for (const bond of bonds) {
    if (bond.kind === 'bond' && !isBondCode(bond.type)) {
      warn(
        'bonds',
        `Bond ${bond.number} is recorded under code "${bond.type}", which is not one ICES has ` +
          '(error 501). Correct it on the bond panel before exporting.',
      );
    }
  }

  return bonds;
}

/**
 * Put each document's eSanchit reference onto the draft's supporting-doc list.
 *
 * A document with no row here keeps its `irn` undefined, which is what makes
 * the SUPPORTING_DOCS mapper warn about it by name instead of filing a row that
 * points at nothing.
 */
function attachEsanchit(
  docs: DraftSupportingDoc[],
  esanchit: EsanchitRow[],
  documents: DocumentRow[],
): DraftSupportingDoc[] {
  // The draft carries file names; the eSanchit rows carry document ids. The
  // job's own document list is what joins them.
  const idByFileName = new Map(documents.map((d) => [d.file_name, d.id]));
  const byDocumentId = new Map(esanchit.map((e) => [e.document_id, e]));

  return docs.map((doc) => {
    const row = byDocumentId.get(idByFileName.get(doc.fileName) ?? '');
    if (!row) return doc;
    return {
      ...doc,
      irn: row.irn,
      uploadedAt: row.uploaded_at,
      ...(row.reference_no && { referenceNo: row.reference_no }),
      ...(row.issued_at && { issuedAt: row.issued_at }),
      ...(row.issue_date && { issueDate: row.issue_date }),
      ...(row.expiry_date && { expiryDate: row.expiry_date }),
      ...(row.invoice_sr_no != null && { invoiceSrNo: row.invoice_sr_no }),
      ...(row.item_sr_no != null && { itemSrNo: row.item_sr_no }),
    };
  });
}
