-- The last three sources the Logi-Sys workbook has no home for: the high-seas
-- chain (HSS), the securities lodged with Customs (BONDS_CERTIFICATES), and the
-- eSanchit reference numbers (SUPPORTING_DOCS).
--
-- All three are operator-held facts that no shipping document carries in full,
-- which is why they are tables rather than extraction output:
--
--   * a high-seas seller's IE Code and branch serial come off the high-seas-sale
--     agreement or the importer's mail, and ICES rejects an unregistered branch
--     (error 163) so there is no safe default;
--   * a bond number and the station it is registered at come off a document
--     Customs issued, and its *state* — credited, expired, closed — is invisible
--     to us entirely (ICES 504, 505, 506), so a number is never carried over
--     from a previous job unconfirmed;
--   * an eSanchit IRN is generated by ICEGATE when the signed PDF is uploaded
--     and exists nowhere else.
--
-- See docs/boe-mapping/16-hss.md, 17-bonds-certificates.md, 18-supporting-docs.md.

-- --------------------------------------------------- the high-seas chain ----

-- One row per party in the chain of sales afloat, ordered by ICES' *preceding
-- level*: 0 is the party who sold to the importer filing the BE, 1 that party's
-- seller. The filing importer is on job_boe_header and is never in this table —
-- putting them here at level 0 shifts every real party down one.
create table public.job_hss_chain (
  id              uuid primary key default gen_random_uuid(),
  company_id      uuid not null references public.companies (id) on delete cascade,
  job_id          uuid not null references public.jobs (id) on delete cascade,

  -- C(1) on the sheet, so the chain cannot exceed ten links.
  level           integer not null check (level between 0 and 9),

  -- ICES looks the party up by IEC (error 161); ten digits, and the leading
  -- zero is part of it.
  iec             text not null check (iec ~ '^[0-9A-Z]{10}$'),
  branch_sr_no    integer check (branch_sr_no > 0),

  -- Optional for a regular IEC, because ICES fills them from its own directory,
  -- and mandatory for one of the exempted-category codes (error 164). The
  -- mapper enforces that split; the column does not, because which codes are
  -- exempted is a list that changes.
  name            text,
  branch_name     text,
  -- The seller's own bank AD code. Reaches no ICES field; Logi-Sys asks anyway.
  ad_code         text,
  address         text,
  city            text,
  country         text,
  postal_code     text,

  source          text not null default 'operator'
    check (source in ('document', 'mail', 'operator')),

  updated_by      uuid references public.profiles (id) on delete set null,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now(),

  -- One party per level: two rows at the same level is ICES error 178.
  unique (job_id, level)
);

create index job_hss_chain_job_idx on public.job_hss_chain (company_id, job_id, level);

-- ------------------------------------------------ bonds and certificates ----

-- The sheet merges two ICES tables, <TABLE>BOND and <TABLE>CERT, and column A
-- picks between them. A bond carries a registration port and no date; a
-- certificate a date and no port — that is the two field lists, not a
-- convention, and it is why this is one table with a discriminator rather than
-- two tables.
create type public.bond_or_certificate as enum ('bond', 'certificate');

create table public.job_bonds_certificates (
  id                uuid primary key default gen_random_uuid(),
  company_id        uuid not null references public.companies (id) on delete cascade,
  job_id            uuid not null references public.jobs (id) on delete cascade,

  seq               integer not null,
  kind              public.bond_or_certificate not null,

  -- A BOND_CODES key on a bond, a CERTIFICATE_TYPES key on a certificate. Both
  -- are C(2); the domains live in packages/core/src/masters/codes.ts, and this
  -- column does not constrain them because the certificate-type directory is
  -- incomplete (open-questions.md#cert-type-ms).
  type              text not null check (type ~ '^[A-Z0-9]{2}$'),

  -- N(10) for a bond and C(30) for a certificate; text either way, because a
  -- bond number's leading zeros are part of it and a certificate number is not
  -- numeric at all (ex_job31: NOC/2026/000004873).
  number            text not null check (length(btrim(number)) between 1 and 30),

  -- Certificates only. <TABLE>BOND has no date field.
  cert_date         date,

  -- The Central Excise jurisdiction, for a certificate produced in lieu of a
  -- bond on an EOU or job-work filing (ICES error 195). Blank otherwise.
  commissionerate   text,
  division          text,
  range_office      text,

  -- Bonds only — the ICES station the bond is registered at, which is not
  -- necessarily where this BE is filed.
  registration_port text,

  -- True when the code was proposed from a licence or a scheme rather than
  -- stated. ex_job26 is an EPCG job whose bond is registered EZ, not EC, so the
  -- scheme-to-bond-code mapping is not one we can assert.
  proposed          boolean not null default false,

  source            text not null default 'operator'
    check (source in ('document', 'mail', 'operator')),

  updated_by        uuid references public.profiles (id) on delete set null,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now(),

  unique (job_id, seq),
  -- The shape rules above, as constraints rather than as comments.
  constraint bond_has_port_not_date check (
    kind <> 'bond' or (cert_date is null and commissionerate is null and division is null and range_office is null)
  ),
  constraint certificate_has_no_port check (
    kind <> 'certificate' or registration_port is null
  )
);

create index job_bonds_certificates_job_idx
  on public.job_bonds_certificates (company_id, job_id, seq);

-- -------------------------------------------- eSanchit document references ----

-- SUPPORTING_DOCS rows are pointers to documents ICEGATE already holds, and the
-- pointer is the IRN. Everything else on the sheet we can derive; the IRN and
-- its upload timestamp exist nowhere but eSanchit, so they are keyed against
-- the job document they belong to.
create table public.job_document_esanchit (
  id             uuid primary key default gen_random_uuid(),
  company_id     uuid not null references public.companies (id) on delete cascade,
  job_id         uuid not null references public.jobs (id) on delete cascade,
  document_id    uuid not null references public.job_documents (id) on delete cascade,

  -- C(16): YYYYMMDD followed by an eight-digit serial. The date inside it
  -- agrees with uploaded_at by construction, which is worth checking — an IRN
  -- whose date disagrees was pasted against the wrong document.
  irn            text not null check (irn ~ '^[0-9]{16}$'),
  uploaded_at    timestamptz not null,

  -- C(17) on the sheet, and the width bites: ex_job31 holds a document name
  -- truncated to exactly seventeen characters.
  reference_no   text check (length(reference_no) <= 17),

  -- Overrides for what the document itself says, when the operator disagrees.
  issued_at      text,
  issue_date     date,
  expiry_date    date,
  -- The six-digit ICEGATE document-type code, when the operator picks one our
  -- DocType domain has no entry for.
  doc_type_code  text check (doc_type_code ~ '^[0-9A-Z]{6}$'),

  -- Which line the document applies to. Both null is the whole Bill of Entry,
  -- which the sheet writes as 0/0.
  invoice_sr_no  integer check (invoice_sr_no > 0),
  item_sr_no     integer check (item_sr_no > 0),

  updated_by     uuid references public.profiles (id) on delete set null,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now(),

  -- One IRN per document, and ICES rejects the same IRN twice against one
  -- invoice (error 832) — across invoices it is expected, so the uniqueness is
  -- on the document, not on the IRN.
  unique (document_id)
);

create index job_document_esanchit_job_idx
  on public.job_document_esanchit (company_id, job_id);

-- ------------------------------------------------------- touch triggers ----

create trigger job_hss_chain_touch_updated_at
  before update on public.job_hss_chain
  for each row execute function public.touch_updated_at();

create trigger job_bonds_certificates_touch_updated_at
  before update on public.job_bonds_certificates
  for each row execute function public.touch_updated_at();

create trigger job_document_esanchit_touch_updated_at
  before update on public.job_document_esanchit
  for each row execute function public.touch_updated_at();

-- ------------------------------------------------------- grants and RLS ----

do $$
declare
  t text;
begin
  foreach t in array array[
    'job_hss_chain',
    'job_bonds_certificates',
    'job_document_esanchit'
  ] loop
    execute format('alter table public.%I enable row level security', t);
    execute format('revoke all on public.%I from anon, authenticated', t);
    execute format('grant select, insert, update, delete on public.%I to service_role', t);
    execute format('grant select on public.%I to authenticated', t);
    execute format($f$
      create policy %1$s_select on public.%1$I
        for select to authenticated
        using (company_id = public.auth_company_id() or public.is_platform_admin())
    $f$, t);
  end loop;
end;
$$;

-- --------------------------------------------------------- document type ----

-- The bank's exchange-rate certificate, for a currency the Ministry of Finance
-- notification does not cover. ICES calls those "non-standard currencies" and
-- makes the bank name, certificate number and certificate date mandatory on the
-- EXCHANGE_RATE row (error 155), with the certificate date equal to the filing
-- date. Nothing read one before, so the columns had no source at all.
alter type public.document_type add value if not exists 'bank_certificate';

-- The high-seas-sale agreement. It is the document the HSS chain is read off,
-- and it classified as 'other' and was discarded while sitting in the job
-- folder — the same failure mode as the shipping bill and the freight
-- certificate before their types were added.
alter type public.document_type add value if not exists 'high_seas_agreement';
